// import { Main } from "next/document";
import Head from "next/head";
import { useState } from "react/cjs/react.development";
import styles from "../styles/Home.module.css";
import Title from "./components/Title";
import Login from "./Login";

export default function Home() {
  const [state, setState] = useState(true);
  const handleLogin = (e) => {
    console.log(e.target);
    if (e.target.matches("h1")) setState(false);
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main onClick={handleLogin} className={styles.main}>
        {state && <Title styles={styles.title} />}
        {!state && <Login className={styles.main} />}
      </main>
    </div>
  );
}
